// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdfopeuoytatpsiwetge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZm9wZXVveXRhdHBzaXdldGdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTQxNDYsImV4cCI6MjA2MDAzMDE0Nn0.eN8sX9xQu_2AQN_D7GmMeLAGdHamWmt6Sdq6sdFd2GI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);